// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-qUJT5yc4MRGUcsJYbhPzrlsIXAey0s',
    appId: '1:273739864453:web:0d636f32d631d1a9da0cec',
    messagingSenderId: '273739864453',
    projectId: 'goldenpos-internship',
    authDomain: 'goldenpos-internship.firebaseapp.com',
    storageBucket: 'goldenpos-internship.appspot.com',
    measurementId: 'G-RT3698WNVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3cCv1J8c5DiwusC7h30HCpRq0fGiUNlM',
    appId: '1:273739864453:android:c349bead0b17ac52da0cec',
    messagingSenderId: '273739864453',
    projectId: 'goldenpos-internship',
    storageBucket: 'goldenpos-internship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmB7J_IcqW9KLs1Pva0HyvPh1qZLLVijI',
    appId: '1:273739864453:ios:f517cef6df967d58da0cec',
    messagingSenderId: '273739864453',
    projectId: 'goldenpos-internship',
    storageBucket: 'goldenpos-internship.appspot.com',
    iosClientId: '273739864453-128s09qslokb3s8l66dki3vtmo99dhll.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastyAppV2',
  );
}
